version: '3'
services:
  web:
    image: myj899/linprob-web
    command: python app.py
    ports:
      - 6000:5000
    volumes:
      - ./flask-app:/opt/flask-app
volumes:
  esdata1:
    driver: local
